### ISSUE TITLE
Release version 0.1

### ISSUE THREAD

**Issue by nikku** [bpmn-io/camunda-modeler-linter-plugin#4]
* [x] Add basic implementation (https://github.com/bpmn-io/camunda-modeler-plugin-linter/issues/1) 
* [x] Basic rules exist (https://github.com/bpmn-io/camunda-modeler-plugin-linter/issues/3)
* [x] Foundations are sufficiently tested (https://github.com/bpmn-io/bpmnlint/issues/4)
* [ ] ~~Add auto fix capabilities (https://github.com/bpmn-io/camunda-modeler-plugin-linter/issues/2)~~

---

Depends on https://github.com/camunda/camunda-modeler/issues/1434
Depends on https://github.com/bpmn-io/bpmn-js-bpmnlint/issues/13
Depends on https://github.com/bpmn-io/camunda-modeler-plugin-linter/issues/1

**Comment by StephenOTT** [comment]
What's the status of this work?  Is there a way to do this with v3 of the modeler?  From the looks of it, the issue is that registerBpmnJsPlugin does not support configuration so you cannot pass the linter config file location when registering the linter plugin.

**Comment by nikku** [comment]
What exactly is your use case? If we know that we can adapt our infrastructure accordingly.

**Comment by StephenOTT** [comment]
Using the linter inside of the modeler desktop app. 

Would expect to be able to set a path to a folder or a file that has all of the lint rules which would be executed

**Comment by nikku** [comment]
To be more precise:

* Do you build your contribute your own lint rule implementation(s)? 

* Do you want to change the rules on the fly (i.e. by updating the config file the Camunda Modeler looks into?

**Comment by StephenOTT** [comment]
We would be building our own rules. But would want them to work in the desultory editor. 

I don't think on the fly is required. Restarting the modeler app would be fine as a first Gen

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/camunda-modeler-linter-plugin/releases/tag/v0.1.0.

Providing custom configuration is supported out of the box, too. Cf. `README`.
